import type { Metadata } from 'next'
import Image from 'next/image'
import 'react-toastify/dist/ReactToastify.css'
// import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="w-full h-screen">
      <Image
        src={'/images/bg-lib.webp'}
        alt="background image"
        className="fixed top-0 -z-10 blur-sm w-full left-0 h-full"
        width={1440}
        height={1024}
      ></Image>
      {children}
    </div>
  )
}
