import NavbarComponent from '@/components/navbar'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Web Truyen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarComponent></NavbarComponent>
        {children}
      </body>
    </html>
  )
}
