import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { DeleteModalProvider } from '../../context/modal/deleteModal.context'
export const metadata: Metadata = {
  title: 'Web Truyen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <DeleteModalProvider>{children}</DeleteModalProvider>
      </body>
    </html>
  )
}
