import type { Metadata } from 'next'
import 'react-toastify/dist/ReactToastify.min.css'
import { DeleteModalProvider } from '../../context/modal/deleteModal.context'
export const metadata: Metadata = {
  title: '1Web Truyen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <DeleteModalProvider>{children}</DeleteModalProvider>
    </div>
  )
}
