import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import Sidebar from './_components/sidebar'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="layout grid grid-cols-12">
          {/* Render sidebar for dashboard */}
          <div className="col-span-3">
            <Sidebar></Sidebar>
          </div>
          {/* header and container */}
          <div className="col-span-9 container px-4 py-2">
            <div className="w-full">header here</div>
            <ToastContainer
              position="top-left"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
